# Generated by Django 4.1.3 on 2023-01-09 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pintpointapi', '0002_alter_tab_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pintpointapi.item')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pintpointapi.tab')),
            ],
        ),
        migrations.AlterField(
            model_name='tab',
            name='items',
            field=models.ManyToManyField(through='pintpointapi.TabItems', to='pintpointapi.item'),
        ),
    ]
